### ISSUE TITLE
Ревью в проекте

### ISSUE THREAD

**Issue by KirGorbunov** [sdilman/YP_MPD_C32_T5_Async_API_1#33]
Проведите ревью 2 заданий своего коллеги по команде. Можно брать задания из спринта по ETL, и первого спринта из модуля "Сервис Async API".

**Comment by sdilman** [comment]
Stepan reviewed Kirill's code:

https://github.com/sdilman/YP_MPD_C32_T5_Async_API_1/pull/45
https://github.com/sdilman/YP_MPD_C32_T5_Async_API_1/pull/29

Kirill reviewed Stepan's code:

https://github.com/sdilman/YP_MPD_C32_T5_Async_API_1/pull/18
https://github.com/sdilman/YP_MPD_C32_T5_Async_API_1/pull/2
