### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [sdilman/YP_MPD_C32_T5_Async_API_1#49]
Хорошо потрудились 👍
Несколько рекомендаций:
1. В скриптах `src/tests/functional/utils` ожидания значения параметров подключений нужно брать из `src/tests/functional/settings.py`. Все настройки должны лежать в одном месте, а не раскиданы по приложению. Имя переменной окружения может измениться, и нам будет удобно исправить это в одном месте, а не выискивать по всему коду.
2. В скриптах ожидания ES и Redis вместо вечного цикла, в который можно попасть при возникновении сложностей, лучше использовать backoff из прошлых спринтов. Он более функционален в сравнении с вечным циклом, теоретически он может сигнализировать команде поддержки после определенного количества попыток.
3. Пустой файл `src/tests/functional/utils/helpers.py` наверное можно убрать
4. В `src/tests/functional/src/test_film.py` в каждом тесте у вас пауза на 3 секунды. Наша задача, в том числе, обеспечивать скорость работы тестов. Их в большом приложении может быть тысячи или даже десятки тысяч, а при таком подходе они будут проходить за сутки, что не очень хорошо и удобно. Вероятно, эти 3 секунды появились там до того, как вы начали использовать `wait_for` при вставке данных в фикстуре. 
5. А какой смысл в этой конструкции?
https://github.com/sdilman/YP_MPD_C32_T5_Async_API_1/blob/4c4676c184cb0661740e5921c9e96170b23a12c4/src/tests/functional/src/test_film.py#L60-L61
6. В `src/api/v1` много раз встречается вот такая конструкция в параметрах методов:

    ```python
    page: int = Query(ge=1, default=1),
    size: int = Query(ge=1, default=50)
    ```
    Можно попробовать вынести эту пару в отдельный класс, какой-нибудь PaginatedParams, инжектить его в качестве зависимости в параметры методов и работать с ними как с объектом. Т.о. параметры пагинации будут в одном месте и при необходимости легко будет их изменить сразу и везде.
7. Вот [тут](https://github.com/sdilman/YP_MPD_C32_T5_Async_API_1/blob/4c4676c184cb0661740e5921c9e96170b23a12c4/src/services/film.py#L212) у вас "захардкожены" redis и ES. А что делать если завтра будет принято решение для кэширования использовать memcached или ES заменить на что-то [другое](https://habr.com/ru/post/581394/).
Эта задача решается использованием абстрактных классов.  
Например таким:
      ```
      class AsyncCacheStorage(ABC):
          @abstractmethod
          async def get(self, key: str, **kwargs):
              pass
      
          @abstractmethod
          async def set(self, key: str, value: str, expire: int, **kwargs):
              pass
      
      ```
      И тогда `redis: Redis = Depends(get_redis)` можно заменить на `cache: AsyncCacheStorage = Depends(RedisRepository),` главное чтобы используемый модуль кэширования реализовывал методы класса AsyncCacheStorage (иногда необходимо написать [адаптер](https://habr.com/ru/post/85095/) ). И если завтра решат перейти на memcached то нам останется лишь изменить  `cache: AsyncCacheStorage = Depends(MemcachedRepository),`. И везде в коде проекта использовать в качестве типа именно `AsyncCacheStorage`. Так мы максимально абстрагируемся от конкретной реализации хранилища.
      Тоже самое и с полнотекстовым поиском можно провернуть.

**Comment by sdilman** [comment]
Closed with https://github.com/sdilman/YP_MPD_C32_T5_Async_API_1/pull/50

**Comment by BigDeepBlue** [comment]
https://github.com/sdilman/YP_MPD_C32_T5_Async_API_1/blob/b65d7062cb61fe02b4bcffdb4323d649c411e865/src/tests/functional/src/test_film.py#L56-L57
